title: Meelad Amouzgar
logo: /assets/img/headshot-circle.png
description: Biological Data Scientist
description: > 
  Scientist: Computational and Systems Biology
  <br><br>
  Experimental and computational biologist experienced in high-dimensional bulk and single-cell data.
  <br><br>
  <a href="https://www.linkedin.com/in/mamouzgar/">View My LinkedIn Profile</a> 
#show_downloads: true
theme: jekyll-theme-minimal
