title: Meelad Amouzgar
logo: /assets/img/headshot-circle.png
description: Computational and Systems Biology
  <a href="https://www.linkedin.com/in/mamouzgar/">View My LinkedIn Profile</a> 
#show_downloads: true
theme: jekyll-theme-minimal
